# player_ratings.R
# Faceoff Impact Score (FIS) leaderboard
# Port of player_ratings.py to R, now using the 10-second post-faceoff window.
#
# Research question:
#   To what extent does a context-weighted FIS provide a more accurate evaluation
#   of player contribution than traditional binary win percentages?
#
# Packages: dplyr, ggplot2, patchwork
# Data:     Sports-analytics/post_faceoff_events_10s.csv

rm(list = ls())
library(dplyr)
library(ggplot2)
library(patchwork)

DATA_FILE   <- "post_faceoff_events_10s.csv"
MIN_FO      <- 50     # minimum faceoffs for a reliable rating
ALPHA_PRIOR <- 10     # Beta(10, 10) prior → shrinks toward 50 % win rate
BETA_PRIOR  <- 10
TERR_SCALE  <- 0.002  # 1 zone step ≈ 0.002 xG; tune to weight territorial vs xG component

# ── 1. LOAD ────────────────────────────────────────────────────────────────────
df <- read.csv(DATA_FILE, stringsAsFactors = FALSE) %>%
  arrange(gameid, compiledgametime)

# ── 2. PHYSICAL FACEOFF ID ─────────────────────────────────────────────────────
# v6 approach: a new faceoff starts when eventname == "faceoff" AND
# compiledgametime changes from the previous row. The two rows of the same
# physical faceoff share identical timestamps, so they get the same ID.
# fill() propagates the ID downward to post-faceoff events within each game.
df <- df %>%
  mutate(
    is_new_faceoff      = as.integer(eventname == "faceoff" &
                                       compiledgametime != lag(compiledgametime, default = 0)),
    physical_faceoff_id = cumsum(is_new_faceoff)
  ) %>%
  group_by(gameid) %>%
  tidyr::fill(physical_faceoff_id, .direction = "downup") %>%
  ungroup()

# ── 3. LEVERAGE SCORE ──────────────────────────────────────────────────────────
period_weights   <- c("1" = 0.6, "2" = 0.8, "3" = 1.0, "4" = 1.5)
manpower_weights <- c("evenStrength" = 1.0, "powerPlay" = 1.3, "shortHanded" = 1.3)

leverage_score <- function(score_diff, period, manpower, fo_x) {
  score_w   <- 1 / (1 + abs(score_diff))
  period_w  <- period_weights[as.character(period)]
  period_w  <- ifelse(is.na(period_w), 1.0, period_w)
  manpower_w <- manpower_weights[manpower]
  manpower_w <- ifelse(is.na(manpower_w), 1.0, manpower_w)
  zone_w    <- ifelse(abs(fo_x) > 25, 1.3, 1.0)
  score_w * period_w * manpower_w * zone_w
}

# ── 3b. ZONE VALUE HELPER ──────────────────────────────────────────────────────
# Maps xadjcoord to an integer zone level from each team's own perspective.
# Scale: -2 (deep own zone) … 0 (center) … +2 (deep offensive zone).
zone_val <- function(x) {
  dplyr::case_when(
    x > 25  ~  2L,   # offensive zone
    x > 5   ~  1L,   # neutral zone (offensive side)
    x > -5  ~  0L,   # center ice
    x > -25 ~ -1L,   # neutral zone (defensive side)
    TRUE    ~ -2L    # defensive zone
  )
}

# ── 4. FACEOFF REGISTRY ─────────────────────────────────────────────────────────
# One row per faceoff with zone, leverage, and both participants.
faceoff_registry <- df %>%
  filter(eventname == "faceoff") %>%
  group_by(gameid, physical_faceoff_id) %>%
  summarise(
    period        = first(period),
    score_diff    = first(scoredifferential),
    manpower      = first(manpowersituation),
    winner_team   = teamid[outcome == "successful"][1],
    loser_team    = teamid[outcome == "failed"][1],
    winner_player = playerid[outcome == "successful"][1],
    loser_player  = playerid[outcome == "failed"][1],
    fo_x          = xadjcoord[outcome == "successful"][1],
    .groups       = "drop"
  ) %>%
  filter(!is.na(winner_team), !is.na(loser_team)) %>%
  mutate(
    leverage = leverage_score(score_diff, period, manpower, fo_x),
    fo_zone  = case_when(
      fo_x > 25 ~ "Offensive Zone",
      fo_x > 5  ~ "Neutral Zone",
      TRUE      ~ "Center Ice"
    )
  )

cat("Faceoffs in registry:", nrow(faceoff_registry), "\n")

# ── 5. XG PER FACEOFF SEQUENCE ─────────────────────────────────────────────────
# For each faceoff, compute total xG generated by winner side and loser side.
xg_by_side <- df %>%
  filter(eventname %in% c("shot", "goal")) %>%
  inner_join(
    faceoff_registry %>% select(gameid, physical_faceoff_id, winner_team, loser_team),
    by = c("gameid", "physical_faceoff_id")
  ) %>%
  mutate(side = case_when(
    teamid == winner_team ~ "xg_winner",
    teamid == loser_team  ~ "xg_loser",
    TRUE                  ~ NA_character_
  )) %>%
  filter(!is.na(side)) %>%
  group_by(gameid, physical_faceoff_id, side) %>%
  summarise(total_xg = sum(xg_allattempts, na.rm = TRUE), .groups = "drop") %>%
  tidyr::pivot_wider(names_from = side, values_from = total_xg, values_fill = 0)

fo_xg <- faceoff_registry %>%
  left_join(xg_by_side, by = c("gameid", "physical_faceoff_id")) %>%
  mutate(
    xg_winner = replace(xg_winner, is.na(xg_winner), 0),
    xg_loser  = replace(xg_loser,  is.na(xg_loser),  0)
  )

# ── 5b. TERRITORIAL DELTA ──────────────────────────────────────────────────────
# For each faceoff, find the furthest zone each team reached within 10 s.
# xadjcoord is always from that team's own attacking perspective, so we can
# compare directly across winner and loser without flipping signs.
# -100 floor ensures faceoffs with zero post-faceoff events map to zone_val = -2.
max_pos <- df %>%
  filter(eventname != "faceoff") %>%
  inner_join(
    faceoff_registry %>% select(gameid, physical_faceoff_id, winner_team, loser_team),
    by = c("gameid", "physical_faceoff_id")
  ) %>%
  group_by(gameid, physical_faceoff_id) %>%
  summarise(
    max_x_winner = max(c(-100, xadjcoord[teamid == first(winner_team)]), na.rm = TRUE),
    max_x_loser  = max(c(-100, xadjcoord[teamid == first(loser_team)]),  na.rm = TRUE),
    .groups = "drop"
  )

fo_xg <- fo_xg %>%
  left_join(max_pos, by = c("gameid", "physical_faceoff_id")) %>%
  mutate(
    max_x_winner = replace(max_x_winner, is.na(max_x_winner), -100),
    max_x_loser  = replace(max_x_loser,  is.na(max_x_loser),  -100),
    # Territorial delta = zone reached - zone started (from each team's perspective).
    # Winner starts at fo_x; loser starts at -fo_x (mirror image of the same spot).
    # DZ win → OZ: winner goes from zone_val(-60) = -2 to zone_val(50) = +2 → delta = +4
    terr_winner = zone_val(max_x_winner) - zone_val(fo_x),
    terr_loser  = zone_val(max_x_loser)  - zone_val(-fo_x)
  )

# ── 6. PER-PLAYER STATS ────────────────────────────────────────────────────────
# Expand to one row per player per faceoff, then aggregate.
player_fo <- bind_rows(
  fo_xg %>% transmute(
    playerid = winner_player, won = TRUE, leverage,
    xg_gen     = xg_winner,
    xg_con     = xg_loser,
    terr_delta = terr_winner
  ),
  fo_xg %>% transmute(
    playerid = loser_player, won = FALSE, leverage,
    xg_gen     = xg_loser,
    xg_con     = xg_winner,
    terr_delta = terr_loser
  )
)

players <- player_fo %>%
  group_by(playerid) %>%
  summarise(
    total_faceoffs = n(),
    wins           = sum(won),
    losses         = sum(!won),
    raw_win_rate   = wins / total_faceoffs,
    lev_xg_gen     = sum(xg_gen[won]  * leverage[won]),
    lev_xg_con     = sum(xg_con[!won] * leverage[!won]),
    # Territorial: leverage-weighted zone delta across ALL faceoffs (won and lost).
    # A DZ win → OZ is +4 x leverage; an OZ loss that collapses to own DZ is -4 x leverage.
    lev_terr       = sum(terr_delta * leverage),
    avg_leverage   = mean(leverage),
    .groups        = "drop"
  ) %>%
  mutate(
    bayes_win_rate = (ALPHA_PRIOR + wins) / (ALPHA_PRIOR + BETA_PRIOR + total_faceoffs),
    FIS_xg         = (lev_xg_gen - lev_xg_con) / total_faceoffs,
    FIS_terr       = (lev_terr * TERR_SCALE)    / total_faceoffs,
    FIS_per_fo     = FIS_xg + FIS_terr
  )

rated <- players %>% filter(total_faceoffs >= MIN_FO)
cat("Players with ≥", MIN_FO, "faceoffs:", nrow(rated), "\n\n")

cat("── Top 10 by FIS per faceoff ─────────────────────────────────────────\n")
print(
  rated %>%
    arrange(desc(FIS_per_fo)) %>%
    select(playerid, total_faceoffs, raw_win_rate, bayes_win_rate, FIS_per_fo) %>%
    head(10) %>%
    mutate(across(where(is.double), \(x) round(x, 4))),
  row.names = FALSE
)

cat("\n── Bottom 10 by FIS per faceoff ──────────────────────────────────────\n")
print(
  rated %>%
    arrange(FIS_per_fo) %>%
    select(playerid, total_faceoffs, raw_win_rate, bayes_win_rate, FIS_per_fo) %>%
    head(10) %>%
    mutate(across(where(is.double), \(x) round(x, 4))),
  row.names = FALSE
)

# ── 7. ANSWERING THE RESEARCH QUESTION ─────────────────────────────────────────
# Correlation between raw win rate and FIS: low correlation = FIS adds information.
cor_raw <- cor(rated$raw_win_rate, rated$FIS_per_fo, method = "spearman")
cor_bay <- cor(rated$bayes_win_rate, rated$FIS_per_fo, method = "spearman")
cat(sprintf("\nSpearman correlation  raw win rate ↔ FIS/fo : %.3f\n", cor_raw))
cat(sprintf("Spearman correlation bayes win rate ↔ FIS/fo : %.3f\n", cor_bay))
cat("(Values < 0.9 indicate FIS captures information win rate does not)\n")

# Identify divergent players: high FIS but below-median win rate (or vice versa)
fis_med <- median(rated$FIS_per_fo)
wr_med  <- median(rated$raw_win_rate)
rated <- rated %>%
  mutate(
    quadrant = case_when(
      raw_win_rate >= wr_med & FIS_per_fo >= fis_med ~ "High win% + High FIS",
      raw_win_rate >= wr_med & FIS_per_fo <  fis_med ~ "High win% + Low FIS",
      raw_win_rate <  wr_med & FIS_per_fo >= fis_med ~ "Low win% + High FIS",
      TRUE                                            ~ "Low win% + Low FIS"
    ),
    outlier = abs(FIS_per_fo) > quantile(abs(FIS_per_fo), 0.92) |
              abs(raw_win_rate - 0.5) > quantile(abs(raw_win_rate - 0.5), 0.92)
  )

# ── 8. PLOT 1: LEADERBOARD ────────────────────────────────────────────────────
# Top 10 + bottom 10, sorted ascending so best is at top.
bottom10 <- rated %>% arrange(FIS_per_fo) %>% slice_head(n = 10)
top10    <- rated %>% arrange(FIS_per_fo) %>% slice_tail(n = 10)
leaderboard_data <- bind_rows(bottom10, top10) %>%
  mutate(
    label     = factor(as.character(playerid), levels = as.character(playerid)),
    bar_color = ifelse(FIS_per_fo >= 0, "positive", "negative"),
    txt_hjust = ifelse(FIS_per_fo >= 0, -0.1, 1.1)
  )

# 6 annotated players: top/mid/bottom of each half
select_three <- function(idx) {
  n <- length(idx)
  if (n == 0) return(integer(0))
  if (n <= 3) return(idx)
  c(idx[1], idx[ceiling(n / 2)], idx[n])
}
annot_idx_pr <- unique(c(select_three(1:10), select_three(11:20)))
fo_annot_pr  <- leaderboard_data[annot_idx_pr, ] %>%
  filter(abs(FIS_per_fo) >= 0.001) %>%
  mutate(fo_label = sprintf("%.0f", 1 / abs(FIS_per_fo)))

p_bar_base <- ggplot(leaderboard_data, aes(x = FIS_per_fo, y = label, fill = bar_color)) +
  geom_col(width = 0.75, show.legend = FALSE) +
  geom_hline(yintercept = 10.5, color = "gray50", linewidth = 0.6, linetype = "dashed") +
  geom_vline(xintercept = 0, color = "black", linewidth = 0.6) +
  scale_fill_manual(values = c("positive" = "#00b894", "negative" = "#8B1A1A")) +
  scale_x_continuous(expand = expansion(mult = c(0.22, 0.22))) +
  labs(x = "FIS per faceoff  (positive = net benefit to team)", y = NULL) +
  theme_minimal(base_size = 12) +
  theme(
    text               = element_text(face = "bold", color = "gray10"),
    panel.grid.major.y = element_blank()
  )

p_bar <- p_bar_base +
  geom_text(
    aes(label = sprintf("%.0f%% win", raw_win_rate * 100), hjust = txt_hjust),
    size = 3.2, color = "black", fontface = "bold"
  )

if (nrow(fo_annot_pr) > 0) {
  fo_pos_pr <- filter(fo_annot_pr, FIS_per_fo >= 0)
  fo_neg_pr <- filter(fo_annot_pr, FIS_per_fo <  0)
  if (nrow(fo_pos_pr) > 0)
    p_bar <- p_bar + geom_text(data = fo_pos_pr,
      aes(x = FIS_per_fo / 2, y = label, label = fo_label),
      size = 3.0, color = "black", fontface = "bold", hjust = 0.5, inherit.aes = FALSE)
  if (nrow(fo_neg_pr) > 0)
    p_bar <- p_bar + geom_text(data = fo_neg_pr,
      aes(x = FIS_per_fo / 2, y = label, label = fo_label),
      size = 3.0, color = "white", fontface = "bold", hjust = 0.5, inherit.aes = FALSE)
}

# ── 9. PLOT 2: WIN RATE VS FIS ────────────────────────────────────────────────
p_scatter_base <- ggplot(rated, aes(x = raw_win_rate, y = FIS_per_fo)) +
  geom_hline(yintercept = 0,   color = "gray50", linetype = "dashed") +
  geom_vline(xintercept = 0.5, color = "gray50", linetype = "dashed") +
  geom_point(aes(color = quadrant, size = total_faceoffs), alpha = 0.85) +
  scale_color_manual(
    values = c(
      "High win% + High FIS" = "#00b894",
      "High win% + Low FIS"  = "#e67e22",
      "Low win% + High FIS"  = "#2980b9",
      "Low win% + Low FIS"   = "#d63031"
    ),
    name = NULL, drop = FALSE
  ) +
  scale_size_continuous(range = c(2, 5), name = "Faceoffs taken") +
  labs(x = "Faceoff win rate", y = "Faceoff Impact Score (FIS) per faceoff") +
  theme_minimal(base_size = 12) +
  theme(
    text            = element_text(face = "bold", color = "gray10"),
    legend.position = "bottom",
    legend.box      = "vertical"
  ) +
  guides(
    color = guide_legend(nrow = 1, override.aes = list(alpha = 1)),
    size  = guide_legend(nrow = 1)
  )

p_scatter <- p_scatter_base +
  geom_text(
    data = filter(rated, outlier),
    aes(label = as.character(playerid)),
    size = 2.8, color = "gray10", fontface = "bold", vjust = -1.1,
    check_overlap = TRUE
  )

# ── 10. COMBINE AND SAVE ──────────────────────────────────────────────────────
combined <- (p_bar | p_scatter) +
  plot_layout(guides = "collect") &
  theme(
    legend.position = "bottom",       # Moves collected legend to the bottom
    legend.box = "vertical",           # Stacks size and color legends
    legend.justification = "center",  # Centers everything perfectly
    legend.margin = margin(t = 10)    # Adds a little breathing room above the legend
  )

ggsave("player_ratings.png", combined,
       width = 16, height = 14, dpi = 150, bg = "white")
message("Saved → player_ratings.png")

ggsave("player_ratings_leaderboard.png", p_bar + labs(x = NULL, y = NULL),
       width = 8, height = 10, dpi = 150, bg = "white")
message("Saved → player_ratings_leaderboard.png")

ggsave("player_ratings_leaderboard_labeled.png", p_bar,
       width = 8, height = 10, dpi = 150, bg = "white")
message("Saved → player_ratings_leaderboard_labeled.png")

ggsave("player_ratings_scatter.png", p_scatter + labs(x = NULL, y = NULL),
       width = 8, height = 8,  dpi = 150, bg = "white")
message("Saved → player_ratings_scatter.png")

ggsave("player_ratings_scatter_labeled.png", p_scatter,
       width = 8, height = 8,  dpi = 150, bg = "white")
message("Saved → player_ratings_scatter_labeled.png")

# ── 12. SAVE RATINGS CSV ───────────────────────────────────────────────────────
rated %>%
  select(playerid, total_faceoffs, wins, losses, raw_win_rate, bayes_win_rate,
         lev_xg_gen, lev_xg_con, lev_terr, FIS_xg, FIS_terr, FIS_per_fo, avg_leverage, quadrant) %>%
  arrange(desc(FIS_per_fo)) %>%
  write.csv("player_ratings.csv", row.names = FALSE)
message("Saved → player_ratings.csv")
